spring:
       jpa:
           properties:
                      hibernate:
                                hbm2ddl:
                                        auto: update
                                naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
           show-sql: true
           open-in-view: true
       datasource:
                 driverClassName: com.mysql.jdbc.Driver
                 url: jdbc:mysql://120.92.119.61:3306/summer?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                 username: root
                 password: 123456
       resources:
         static-locations: classpath:/,classpath:/templates/
       redis:
         database: 0
         host: localhost
         password:
         port: 6379
         jedis:
           pool:
             max-idle: 8
             min-idle: 0
             max-active: 8
#             max-wait: -1

server:
  servlet:
    context-path: /
  port: 8081


